### ISSUE TITLE
Fitting Models to New Data Fails

### ISSUE THREAD

**Issue by gdreiman-insitro** [ersilia-os/zaira-chem#26]
**Describe the bug**
I'm trying to fit a model to a set of binary labeled smiles. I've replicated the desired csv format, but I eventually hit a snag with `ersilia`,  when I try `zairachem fit -i demo_errors.csv -m model`. I've include the full trace below, but the heart of the issue seems to be that here in [line 152](https://github.com/ersilia-os/ersilia/blob/master/ersilia/io/input.py#L153), `none` is passed as `config_json`. This means that in `GenericInputAdapter`'s `self.adapter.adapt` returns `none` at [line 172](https://github.com/ersilia-os/ersilia/blob/master/ersilia/io/input.py#L172).

Traceback:
```
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/zairachem/bin/zairachem", line 33, in <module>
    sys.exit(load_entry_point('zairachem', 'console_scripts', 'zairachem')())
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ec2-user/zaira-chem/zairachem/cli/commands/fit.py", line 126, in fit
    d.run()
  File "/home/ec2-user/zaira-chem/zairachem/descriptors/describe.py", line 67, in run
    self._reference_descriptors()
  File "/home/ec2-user/zaira-chem/zairachem/descriptors/describe.py", line 48, in _reference_descriptors
    ReferenceDescriptors().run()
  File "/home/ec2-user/zaira-chem/zairachem/descriptors/reference.py", line 46, in run
    ref.calculate(self.smiles_list, output_h5)
  File "/home/ec2-user/zaira-chem/zairachem/descriptors/baseline.py", line 82, in calculate
    X = self._calculate(smiles_list, output_h5)
  File "/home/ec2-user/zaira-chem/zairachem/descriptors/baseline.py", line 79, in _calculate
    mdl.api(api_name=None, input=smiles_list, output=output_h5)
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/ersilia/core/model.py", line 354, in api
    api_name=api_name, input=input, output=output, batch_size=batch_size
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/ersilia/core/model.py", line 368, in api_task
    for r in result:
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/ersilia/core/model.py", line 194, in _api_runner_iter
    for result in api.post(input=input, output=output, batch_size=batch_size):
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 319, in post
    unique_input, mapping = self._unique_input(input)
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 279, in _unique_input
    for i, inp in enumerate(self.input_adapter.adapt_one_by_one(input)):
  File "/home/ec2-user/miniconda3/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 173, in adapt_one_by_one
    for d in data:
TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
Some python to make a demo dataset using TDC: 
```
from tdc.benchmark_group import admet_group
import pandas as pd
from numpy import random
group = admet_group(path = 'data/')
benchmark = group.get('Caco2_Wang')
train_val = benchmark['train_val']
demo_df = pd.DataFrame({'smiles':train_val['Drug'].tolist(),'activity': random.randint(0,2,len(train_val))})
demo_df.to_csv('demo_errors.csv')
```
Then run 
```
zairachem fit -i demo_errors.csv -m model
```

**Expected behavior**
I think that there should be some default config maybe? Or a better doc of what `self.adapter.adapt` should do so I can hack around it.

**Comment by GemmaTuron** [comment]
Hi @gdreiman-insitro 

Thanks for opening this issue. Might I ask if you have tried to simply run a test of Ersilia? Could you please try:
```
conda activate zairachem
ersilia -v fetch eos3b5e
ersilia -v serve eos3b5e
ersilia -v api -i "CCCCCN" 
```
This will tell us if there is an issue with your install of Ersilia or the error lies within the Zaira Chem code.

**Comment by sooheon** [comment]
Following those steps gives me the same error as #27 

```
(zairachem) stillwork@dilab248:~/code/zaira-chem$ ersilia -v api -i "CCCCCN"
/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
17:31:36 | DEBUG    | Getting session from /home/stillwork/eos/session.json
17:31:36 | DEBUG    | Getting session from /home/stillwork/eos/session.json
17:31:36 | DEBUG    | Is fetched: True
17:31:36 | DEBUG    | Schema available in /home/stillwork/eos/dest/eos3b5e/api_schema.json
17:31:36 | DEBUG    | Setting AutoService for eos3b5e
17:31:36 | INFO     | Service class provided
17:31:37 | DEBUG    | No file splitting necessary!
17:31:37 | DEBUG    | Reading card from eos3b5e
17:31:37 | DEBUG    | Reading shape from eos3b5e
17:31:37 | DEBUG    | Input Shape: Single
17:31:37 | DEBUG    | Input type is: compound
17:31:37 | DEBUG    | Input shape is: Single
17:31:37 | DEBUG    | Importing module: .types.compound
17:31:37 | DEBUG    | Checking RDKIT and other requirements necessary for compound inputs
17:31:37 | DEBUG    | InputShapeSingle shape: Single
17:31:37 | DEBUG    | API eos3b5e:run initialized at URL http://127.0.0.1:46819
17:31:37 | DEBUG    | Schema available in /home/stillwork/eos/dest/eos3b5e/api_schema.json
17:31:37 | DEBUG    | No file splitting necessary!
17:31:37 | DEBUG    | Reading card from eos3b5e
17:31:37 | DEBUG    | Reading shape from eos3b5e
17:31:37 | DEBUG    | Input Shape: Single
17:31:37 | DEBUG    | Input type is: compound
17:31:37 | DEBUG    | Input shape is: Single
17:31:37 | DEBUG    | Importing module: .types.compound
17:31:37 | DEBUG    | Checking RDKIT and other requirements necessary for compound inputs
17:31:37 | DEBUG    | InputShapeSingle shape: Single
17:31:37 | DEBUG    | API eos3b5e:run initialized at URL http://127.0.0.1:46819
17:31:37 | DEBUG    | Schema available in /home/stillwork/eos/dest/eos3b5e/api_schema.json
17:31:37 | DEBUG    | Posting to run
17:31:37 | DEBUG    | Batch size 100
17:31:37 | DEBUG    | Schema available in /home/stillwork/eos/dest/eos3b5e/api_schema.json
17:31:37 | DEBUG    | Checking for already available calculations in the data lake
17:31:37 | DEBUG    | Inspecting 0...
17:31:37 | DEBUG    | Calculating using model eos3b5e
17:31:37 | DEBUG    | Saving in /tmp/ersilia-hrz_p8zn/todo_output.json
17:31:37 | DEBUG    | Expected number: 1
17:31:37 | DEBUG    | Entity is list: False
17:31:37 | DEBUG    | Resolving columns
17:31:37 | DEBUG    | Done with sniffing the file
17:31:37 | DEBUG    | Input: {2: 1, 3: 1}
17:31:37 | DEBUG    | Key: {1: 1}
17:31:37 | DEBUG    | Key: [1]
17:31:37 | DEBUG    | Input: [2]
17:31:37 | DEBUG    | Candidate header is ['0', 'DPBLXKKOBLCELK-UHFFFAOYSA-N', 'CCCCCN', 'CCCCCN']
17:31:37 | DEBUG    | Matching for input is [2]
17:31:37 | DEBUG    | Has header False
17:31:37 | DEBUG    | Schema {'input': [2], 'key': [1]}
Traceback (most recent call last):
  File "/home/stillwork/.conda/envs/zairachem/bin/ersilia", line 8, in <module>
    sys.exit(cli())
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/cli/commands/__init__.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/cli/commands/api.py", line 42, in api
    api_name=api_name, input=input, output=output, batch_size=batch_size
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/core/model.py", line 195, in _api_runner_iter
    for result in api.post(input=input, output=output, batch_size=batch_size):
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 320, in post
    input=unique_input, output=None, batch_size=batch_size
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 296, in post_unique_input
    for res in self.post_amenable_to_h5(input, output, batch_size):
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 249, in post_amenable_to_h5
    input=todo_input, output=todo_output, batch_size=batch_size
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 126, in post_only_calculations
    for input in self.input_adapter.adapt(input, batch_size=batch_size):
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 167, in adapt
    data = self.adapter.adapt(inp)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 144, in adapt
    data = self._adapt(inp)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 138, in _adapt
    return self._file_reader(inp)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 130, in _file_reader
    reader = TabularFileReader(path=inp, IO=self.IO)
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/io/readers/file.py", line 570, in __init__
    self._standardize()
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/io/readers/file.py", line 579, in _standardize
    sniff_line_limit=self.sniff_line_limit,
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/io/readers/file.py", line 409, in __init__
    self.read_input_columns()
  File "/home/stillwork/.conda/envs/zairachem/lib/python3.7/site-packages/ersilia/io/readers/file.py", line 321, in read_input_columns
    if len(h) == 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by GemmaTuron** [comment]
This issue will be closed due to inactivity. If there is further assistance needed, please feel free to reopen it @gdreiman-insitro
