### ISSUE TITLE
zairachem fit with example data errors: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sooheon** [ersilia-os/zaira-chem#27]
**Describe the bug**
Just following example, `fit` will throw TypeError.

**To Reproduce**
Follow the example at: https://ersilia.gitbook.io/ersilia-book/chemistry-tools/automated-activity-prediction-models/accurate-automl-with-zairachem

**Screenshots**
```
Traceback (most recent call last):
  File "/home/sooh/mambaforge/envs/zairachem/bin/zairachem", line 33, in <module>
    sys.exit(load_entry_point('zairachem', 'console_scripts', 'zairachem')())
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sooh/zaira-chem/zairachem/cli/commands/fit.py", line 126, in fit
    d.run()
  File "/home/sooh/zaira-chem/zairachem/descriptors/describe.py", line 67, in run
    self._reference_descriptors()
  File "/home/sooh/zaira-chem/zairachem/descriptors/describe.py", line 48, in _reference_descriptors
    ReferenceDescriptors().run()
  File "/home/sooh/zaira-chem/zairachem/descriptors/reference.py", line 46, in run
    ref.calculate(self.smiles_list, output_h5)
  File "/home/sooh/zaira-chem/zairachem/descriptors/baseline.py", line 79, in calculate
    X = self._calculate(smiles_list, output_h5)
  File "/home/sooh/zaira-chem/zairachem/descriptors/baseline.py", line 76, in _calculate
    mdl.api(api_name=None, input=smiles_list, output=output_h5)
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/core/model.py", line 354, in api
    api_name=api_name, input=input, output=output, batch_size=batch_size
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/core/model.py", line 368, in api_task
    for r in result:
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/core/model.py", line 195, in _api_runner_iter
    for result in api.post(input=input, output=output, batch_size=batch_size):
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 320, in post
    input=unique_input, output=None, batch_size=batch_size
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 296, in post_unique_input
    for res in self.post_amenable_to_h5(input, output, batch_size):
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 249, in post_amenable_to_h5
    input=todo_input, output=todo_output, batch_size=batch_size
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/serve/api.py", line 126, in post_only_calculations
    for input in self.input_adapter.adapt(input, batch_size=batch_size):
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 167, in adapt
    data = self.adapter.adapt(inp)
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 144, in adapt
    data = self._adapt(inp)
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 138, in _adapt
    return self._file_reader(inp)
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/io/input.py", line 130, in _file_reader
    reader = TabularFileReader(path=inp, IO=self.IO)
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/io/readers/file.py", line 570, in __init__
    self._standardize()
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/io/readers/file.py", line 579, in _standardize
    sniff_line_limit=self.sniff_line_limit,
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/io/readers/file.py", line 409, in __init__
    self.read_input_columns()
  File "/home/sooh/mambaforge/envs/zairachem/lib/python3.7/site-packages/ersilia/io/readers/file.py", line 321, in read_input_columns
    if len(h) == 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by GemmaTuron** [comment]
Hi @sooheon 

Thanks for filing this issue report. Could you please provide details about your system? Are you running a Linux machine? and which Py version so we can provide dedicated support?

**Comment by sooheon** [comment]
Linux. Everything installed the default zairachem install script, so python3.7

I've found it's this commit https://github.com/ersilia-os/ersilia/commit/9c3c2aaf62a194487e8c7f67a64a8ff7e7f24fc4 that causes the problem, so changing the line 39 in `install_linux.sh` to `python3 -m pip install git+https://github.com/ersilia-os/ersilia.git@v0.1.24` resolves the issue.

**Comment by GemmaTuron** [comment]
Hi @sooheon 

That is very helpful thanks. We keep developing Ersilia so inconsistencies might appear. I will pin the version for zairachem as you suggest

**Comment by GemmaTuron** [comment]
Hi @sooheon 

That is very helpful thanks. We keep developing Ersilia so inconsistencies might appear. I will pin the version for zairachem as you suggest

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola do we think we can close this issue with the latest updates we have done?

**Comment by miquelduranfrigola** [comment]
Presumably yes, but I haven't tested. I would close the issue and we can reopen if we encounter the same error.
